/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 moon.glb --transform 
Files: moon.glb [1.12MB] > C:\Users\ELOHOME LTD\Desktop\Projects\final-portfolio\portfolio-frontend\public\moon-transformed.glb [70.31KB] (94%)
Author: SIGlab_poly (https://sketchfab.com/siglab_poly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/moon-80e627c01a1b4700a29426253c1d7104
Title: Moon
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations, Bounds } from '@react-three/drei'

export default function MoonLight(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/moon-transformed.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // Play all animations
    Object.values(actions).forEach(action => {
      if (action) {
        action.play();
      }
    });

    // Cleanup animations when component unmounts
    return () => {
      Object.values(actions).forEach(action => {
        if (action) {
          action.stop();
        }
      });
    };
  }, [actions]);

  return (
      <Bounds fit clip damping={6} margin={1}>
        <group ref={group} {...props} dispose={null}>
          <group name="Sketchfab_Scene">
            <group name="RootNode" scale={0.019}>
              <group
                  name="pSphere1"
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={8.547}
              >
                <mesh
                    name="pSphere1_lambert2_0"
                    geometry={nodes.pSphere1_lambert2_0.geometry}
                    material={materials.lambert2}

                />
              </group>
            </group>
          </group>
        </group>
      </Bounds>
  )
}

useGLTF.preload('/moon.glb')
