/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 planet.glb --transform 
Files: planet.glb [5.9MB] > C:\Users\ELOHOME LTD\Desktop\Projects\linux-proj\linuxport\public\planet-transformed.glb [3.6MB] (39%)
*/

import React, {useEffect} from 'react'
import {useGLTF, useAnimations, OrbitControls} from '@react-three/drei'

export default function Planet(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/planet-transformed.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // Play all animations
    Object.values(actions).forEach(action => {
      if (action) {
        action.play();
      }
    });

    // Cleanup animations when component unmounts
    return () => {
      Object.values(actions).forEach(action => {
        if (action) {
          action.stop();
        }
      });
    };
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null} position={[0, -15,0]}
           scale={0.4}
           rotation={[Math.PI, -1.395, Math.PI]}>
      <group name="Crater">
        <group name="group" position={[-47.5, 24.972, -39]} scale={0.25}>
          <group name="pSphere2" rotation={[0, 0.834, 0]} scale={1.9}>
            <mesh name="pSphere2_phong2_0" geometry={nodes.pSphere2_phong2_0.geometry} material={materials.phong2} />
          </group>
          <group name="pSphere3" rotation={[-Math.PI, 0.68, -Math.PI]} scale={4.75}>
            <mesh name="pSphere3_phong3_0" geometry={nodes.pSphere3_phong3_0.geometry} material={materials.phong3} />
          </group>
          <group name="pSphere4" rotation={[0, -0.926, 0]} scale={5}>
            <mesh name="pSphere4_phong4_0" geometry={nodes.pSphere4_phong4_0.geometry} material={materials.phong4} />
          </group>
          <group name="pSphere5" rotation={[Math.PI, -0.708, Math.PI]} scale={2.65}>
            <mesh name="pSphere5_phong5_0" geometry={nodes.pSphere5_phong5_0.geometry} material={materials.phong5} />
          </group>
          <group name="pSphere6" rotation={[0, 0.523, 0]} scale={28}>
            <mesh name="pSphere6_phong6_0" geometry={nodes.pSphere6_phong6_0.geometry} material={materials.phong6} />
          </group>
          <group name="pSphere7" rotation={[-Math.PI, 1.151, -Math.PI]} scale={19}>
            <group name="pCylinder1" position={[0, 0, 18.158]} scale={0.934}>
              <mesh name="pCylinder1_phong10_0" geometry={nodes.pCylinder1_phong10_0.geometry} material={materials.phong10} />
            </group>
            <mesh name="pSphere7_phong7_0" geometry={nodes.pSphere7_phong7_0.geometry} material={materials.phong7} />
          </group>
          <group name="pSphere8" rotation={[Math.PI, -1.395, Math.PI]} scale={8}>
            <mesh name="pSphere8_phong8_0" geometry={nodes.pSphere8_phong8_0.geometry} material={materials.phong8} />
          </group>
          <group name="pSphere9" rotation={[0, -0.298, 0]} scale={7.8}>
            <mesh name="pSphere9_phong9_0" geometry={nodes.pSphere9_phong9_0.geometry} material={materials.phong9} />
          </group>
        </group>
        <points name="Object_2" geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} position={[-6.384, -155.911, 76.306]} rotation={[-Math.PI / 2, -1.022, 0]} scale={0.001} />
        <mesh name="navMesh" geometry={nodes.navMesh.geometry} material={nodes.navMesh.material} position={[0, 0.005, 0]} />
        <mesh name="trimesh" geometry={nodes.trimesh.geometry} material={nodes.trimesh.material} position={[0, 0.005, 0]} />
        <mesh name="pCylinder10_phong11_0" geometry={nodes.pCylinder10_phong11_0.geometry} material={materials.phong11} position={[-47.5, 24.972, -39]} scale={0.25} />
        <mesh name="pSphere1_phong1_0" geometry={nodes.pSphere1_phong1_0.geometry} material={materials.phong1} position={[-47.5, 24.972, -39]} scale={35} />
      </group>
      <OrbitControls
          enableZoom={false}
          enablePan={false}
          autoRotate
          autoRotateSpeed={0.5}
      />
    </group>
  )
}

useGLTF.preload('/planet.glb')
